<?php require APPROOT . '/views/inc/header.php'; ?>
  <h1><?php echo $data['title']; ?></h1>
  <div class="row p-3 mb-3">
    <p>Situated in the beautiful Vale of Clwyd, North Wales, Bodfari Records are proud to present a local geneaology resource / website containing parish records from St Stephen's Church, Bodfari, along with its associated national census reports.</p>
    <p>If you've been researching genealogy for any length of time, you've probably heard the advice that you need to evaluate evidence, but what does that really mean? Let's see what it really means to evaluate evidence. Are we looking at validated evidence, is it hearsay, my mum told me?? </p>    <p>Given the massive growth of interest in family history research in recent years, a very large number of sources have appeared which supplement those which were there all along and which can be utilized by the researcher. In addition, these sources have become easier to access, though one needs to pay a modest fee for the use of some of them. Many of them also are directed towards family history, but when researching properties they are just as useful, properties often being of interest due to the people associated with them. First find the people, and then we learn something of the property history.",</p>
    <h5>With over 21,000 records currently.</h5>
    <p>On this website we have sections on Baptisms, Funerals, Marriages and several copies of the early Census reports. All of our information has been transcribed from local Parsh records and or other validated sources.</p>
    <p>There is also a section where you can post questions or share local geneaology information with each other, some might call it a Blog. Just be aware  this is a local resource, run by enthusiastic volunteers who give their time to maintain and run this website.</p>
    <h5>St Stephens Parish Church Ledgers: 1571 - 2009</h5>
    <p>What do our records contain? Well maybe not all of the above but we do have over 21,00 records, not bad for a local Geneaology website for the Bodfari Parish. It has sections from the Parish ledgers of St Stephens Church, Bodfari on Baptisms with 6100 records, Funerals with 6900 records and Marriages with 2500 records. There are several copies of the early Census reports that cover a 60 year period from 1841 through to 1901 and contain another 5500 records!!</p>
    <p>On this website you have search access to four comprehensive local databases. At present each is contained in isolation to minimise the complexity of searching across multiple tables of data.</p>
    <h5>The East Wing at Grove Hall</h5>
    <p><img src="../img/grovehall.jpg" alt="Responsive image" class="img-fluid max-width:100% rounded-circle float-right" width="450">Looking to visit the beautiful Vale of Clwyd or do some research in and around St Stephen's Church? Why not take a look at "The East Wing at Grove Hall" which is perched on the hilside overlooking St Stephen's Church, Bodfari and the Vale of Clwyd.<br><br>The East Wing at Grove Hall is available to rent, so why not stay and study your geaneology with the "Master" himself.  <a href="https://www.welcomecottages.com/cottages/the-east-wing-at-grove-hall-uk10176?bathrooms=4">Click here to check availability.</a></p> 
    <p>Version: <strong><?php echo APPVERSION; ?></strong></p>
  </div>
<?php require APPROOT . '/views/inc/footer.php'; ?>
